version: '3'

services:
  config:
    image: com.fsd.support.services/config-server:0.0.1-SNAPSHOT
    ports:
        - "8888"
  discovery:
      image: com.fsd.support.services/discovery-server:0.0.1-SNAPSHOT
      ports:
          - "8761"
      environment:
          - JAVA_OPTS= -Dspring.profiles.active=docker
      links:
        - config
