version: '3'

services:
  config:
    image: fsdapps/config-server:0.0.1-SNAPSHOT
    ports:
    - 8888:8888
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
  discovery:
    image: fsdapps/discovery-server:0.0.1-SNAPSHOT
    ports:
    - 8761:8761
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    links:
    - config
  edge:
    image: fsdapps/edge-server:0.0.1-SNAPSHOT
    ports:
    - 8765:8765
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    links:
    - config
    - discovery
  histrix:
    image: fsdapps/hystrix-dashboard:0.0.1-SNAPSHOT
    ports:
    - 7979:7979
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    links:
    - config
    - discovery
  turbine:
    image: fsdapps/turbine-server:0.0.1-SNAPSHOT
    ports:
    - 8989:8989
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    links:
    - config
    - discovery
  auth:
    image: fsdapps/auth-server:0.0.1-SNAPSHOT
    ports:
    - 9090:9090
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    links:
    - config
    - discovery