version: '3'

services:
  config:
    image: fsdapps/config-server:0.0.1-SNAPSHOT
    ports:
    - 8888
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
  discovery:
    image: fsdapps/discovery-server:0.0.1-SNAPSHOT
    ports:
    - 8761
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - SPRING_PROFILES_ACTIVE=docker
    links:
    - config
    depends_on:
    - config
  edge:
    image: fsdapps/edge-server:0.0.1-SNAPSHOT
    ports:
    - 8765
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - SPRING_PROFILES_ACTIVE=docker
    links:
    - config
    - discovery
    depends_on:
    - config
    - discovery
  histrix:
    image: fsdapps/hystrix-dashboard:0.0.1-SNAPSHOT
    ports:
    - 7979
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - SPRING_PROFILES_ACTIVE=docker
    links:
    - config
    - discovery
    depends_on:
    - config
    - discovery
    - edge
  turbine:
    image: fsdapps/turbine-server:0.0.1-SNAPSHOT
    ports:
    - 8989
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    links:
    - config
    - discovery
    depends_on:
    - config
    - discovery
    - edge
  auth:
    image: fsdapps/auth-server:0.0.1-SNAPSHOT
    ports:
    - 9090
    links:
    - config
    - discovery
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    depends_on:
    - config
    - discovery
    - edge